# Default Settings
defaults:
  partition: "batch"
  nodes: 1
  ntasks: 1
  cpus_per_task: 16

# HPC Resource
resource_profiles:
  data_manage:
    memory: "2gb"
    time: "00:20:00"

  light_short:
    memory: "16gb"
    time: "04:00:00"
  
  standard:
    memory: "32gb"
    time: "20:00:00"
  
  standard_short:
    memory: "32gb"
    time: "08:00:00"
  
  heavy_long:
    memory: "64gb"
    time: "24:00:00"

# Analysis and Prep Pipeline
tasks:
  prep:
    - name: unzip
      profile: standard
      scripts: [unzip_rename.sh]
      output_pattern: "{base_output}/raw"
    
    - name: recon_bids
      profile: light_short
      array: true
      scripts: [dcm2bids_convert_BIDS.sh]
      input_from: unzip
      output_pattern: "{base_output}/BIDS"
    
    # - name: field_map_sdc
    #   profile: standard_short
    #   array: true
    #   scripts: [compute_filedmap_sdc]
    #   input_from: recon_bids
    #   output_pattern: "{base_output}/field_map/sdc"
    
    # - name: field_map_fsl_afni
    #   profile: standard_short
    #   array: true
    #   scripts: [bias_field_correction]
    #   input_from: recon_bids
    #   output_pattern: "{base_output}/field_map/fsl_afni"

  # Structural MRI
  structural:
    - name: afni_volume
      profile: standard_short
      array: true
      input_from: recon_bids
      scripts: [sswarp_scratch.sh]
      output_pattern: "{base_output}/AFNI_derivatives"

  # Resting State fMRI - fMRIPrep
  rest_fmriprep:
    - name: rest_fmriprep_preprocess
      profile: heavy_long
      array: true
      input_from: recon_bids
      scripts: [fmriprep_rs.sh]
      output_pattern: "{base_output}/BIDS_derivatives/fmriprep"
    
    - name: rest_fmriprep_post_fc
      profile: standard_short
      array: true
      input_from: rest_fmriprep_preprocess
      scripts: [xcpd_rs.sh]
      output_pattern: "{base_output}/BIDS_derivatives/xcpd"
    
    # - name: rest_fmriprep_post_graph_theory
    #   profile: standard_short
    #   array: true
    #   input_from: rest_fmriprep_post_fc
    #   scripts: [rest_fmriprep_xcpd_graph]
    #   output_pattern: "{base_output}/BIDS_derivatives/graph_theory"

  # Task fMRI - AFNI
  task_afni:
    - name: cards_preprocess
      profile: standard
      array: true
      input_from: recon_bids
      scripts: [afni_cards_preprocessing.sh]
      output_pattern: "{base_output}/AFNI_derivatives"
    
    - name: kidvid_preprocess
      profile: standard
      array: true
      input_from: recon_bids
      scripts: [afni_kidvid_preprocess.sh]
      output_pattern: "{base_output}/AFNI_derivatives"

  # Task dwi
  task_dti:
    - name: dwi_preprocess
      profile: standard
      array: true
      input_from: recon_bids
      scripts: [qsiprep.sh]
      output_pattern: "{base_output}/DTI_derivatives/qsiprep"

    - name: dwi_post
      profile: standard
      array: true
      input_from: dwi_preprocess
      scripts: [qsirecon.sh]
      output_pattern: "{base_output}/DTI_derivatives/qsirecon"

  # Quality control
  qc:
    - name: mriqc_individual
      profile: heavy_long
      array: true
      input_from: recon_bids
      scripts: [mriqc_individual.sh]
      output_pattern: "{base_output}/quality_control/mriqc"

    - name: mriqc_group
      profile: light_short
      input_from: recon_bids # recon_bids is the correct one, not mriqc_individual
      scripts: [mriqc_group.sh]
      output_pattern: "{base_output}/quality_control/mriqc"

  # Database
  # merge_logs:
  #   - name: merge_logs
  #     profile: data_manage
  #     scripts: [merge_logs.py]

# array jobs
array_config:
  pattern: "1-{num}%15"